User is redirected to Home Page after logging out
HoanVanHuynh/test-cases-selenium-framework-hoan pull request #6
Opened 2021-09-01 09:16 UTC by HoanVanHuynh

User is redirected to Home Page after logging out

2021-09-01 09:22 UTC, tanmle requested changes

2021-09-01 09:22 UTC, tanmle commented on src/main/java/page_objects/BasePage.java
> +    }
there should be a downline between the methods.

2021-09-01 09:22 UTC, tanmle commented on src/main/java/page_objects/BasePage.java
> +        return getTabLogout().isDisplayed();
you should wrap isDisplayed otherwise it will throw exception

2021-09-01 09:22 UTC, tanmle commented on src/main/java/page_objects/BasePage.java
> +    public Boolean isLogoutTabDisplayed() {
is it ok if we use `boolean` instead?

2021-09-01 09:26 UTC, anhlvt approved these changes

2021-09-01 09:32 UTC, HoanVanHuynh commented on src/main/java/page_objects/BasePage.java
> +        return getTabLogout().isDisplayed();
thank you so much, I'll use try , catch

2021-09-01 09:32 UTC, HoanVanHuynh commented on src/main/java/page_objects/BasePage.java
> +    public Boolean isLogoutTabDisplayed() {
I'll change that

2021-09-01 09:33 UTC, HoanVanHuynh commented on src/main/java/page_objects/BasePage.java
> +    }
thank you so much

2021-09-06 03:36 UTC, tanmle commented on src/main/java/page_objects/LoginPage.java
> +        this.getTxtUsername().clear();
why do you need clear before entering? aren't they empty before entering?

2021-09-06 03:41 UTC, HoanVanHuynh commented on src/main/java/page_objects/LoginPage.java
> +        this.getTxtUsername().clear();
Because I want to use that clear function for logging in many times. So please let me know what should I do in that case? Thank you so much.

2021-09-06 03:47 UTC, HoanVanHuynh commented on src/main/java/page_objects/LoginPage.java
> +        this.getTxtUsername().clear();
First time I did not use clear function for login function,  but after I created a loginMultipleTimes I think I should add clear function to remove old username and password

2021-09-06 04:10 UTC, tanmle approved these changes

2021-09-06 04:10 UTC, merged

2021-09-06 04:12 UTC, HoanVanHuynh commented on src/main/java/page_objects/LoginPage.java
> +        this.getTxtUsername().clear();
Thank for the question, I have already deleted two clears before entering.