User can not change password when New Password and Confirm Password a…
HoanVanHuynh/test-cases-selenium-framework-hoan pull request #8
Opened 2021-09-06 10:13 UTC by HoanVanHuynh

User can not change password when New Password and Confirm Password are different

2021-09-06 12:19 UTC, tanmle requested changes

2021-09-06 12:19 UTC, tanmle commented on src/main/java/page_objects/BasePage.java
> +    private final By tabChangePassword = By.cssSelector(" a[href*='ChangePassword']");
why isn't this element consistent with the other tabs?

2021-09-06 12:19 UTC, tanmle commented on src/test/java/tests/RegisterTests.java
> +        String actualError = changePasswordPage.getChangePasswordErrorMessage();
why aren't these var names consistent with the confirm password ones?

2021-09-06 12:47 UTC, HoanVanHuynh commented on src/main/java/page_objects/BasePage.java
> +    private final By tabChangePassword = By.cssSelector(" a[href*='ChangePassword']");
thank you, I'm so sorry, I will delete space before locator a[href*='ChangePassword']

2021-09-06 12:48 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +        String actualError = changePasswordPage.getChangePasswordErrorMessage();
Thank you, I'll rename all those var names

2021-09-07 01:51 UTC, MinhQuan119 commented on src/test/java/tests/RegisterTests.java
> +        String actualChangePasswordErrorAtTop = changePasswordPage.getPasswordErrorMessageAtTop();
Need to check with Hoan about what error it is, variable name so long. Please don't merge it yet

2021-09-07 01:58 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +        String actualChangePasswordErrorAtTop = changePasswordPage.getPasswordErrorMessageAtTop();
Thank you so much, I'll rename it

2021-09-07 02:08 UTC, MinhQuan119 commented on src/test/java/tests/RegisterTests.java
> +        String actualChangePasswordErrorAtTop = changePasswordPage.getPasswordErrorMessageAtTop();
![image](https://user-images.githubusercontent.com/23515968/132273363-381882ed-dc1f-4354-b3fe-75575c6ea6e2.png)

In this case, it can be actualFormErrorMsg

2021-09-07 02:09 UTC, MinhQuan119 commented on src/test/java/tests/RegisterTests.java
> +        String actualConfirmPasswordErrorNextTo = changePasswordPage.getConfirmPasswordErrorMessageNextTo();
This variable can be changed to actualConfirmPasswordErrorMsg

2021-09-07 02:24 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +        String actualConfirmPasswordErrorNextTo = changePasswordPage.getConfirmPasswordErrorMessageNextTo();
Thank you so much

2021-09-07 02:24 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +        String actualChangePasswordErrorAtTop = changePasswordPage.getPasswordErrorMessageAtTop();
Thank you so much

2021-09-07 02:26 UTC, MinhQuan119 approved these changes

2021-09-07 02:27 UTC, MinhQuan119 approved these changes

2021-09-07 03:07 UTC, anhlvt commented on src/test/java/tests/RegisterTests.java
> +
What happen when we run all test class one time?

2021-09-07 03:08 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
Thank you for the question, in my case it'll run without error

2021-09-07 03:09 UTC, anhlvt commented on src/test/java/tests/RegisterTests.java
> +
I don't think so

2021-09-07 03:20 UTC, tanmle commented on src/main/java/page_objects/BasePage.java
> +    private final By tabChangePassword = By.cssSelector(" a[href*='ChangePassword']");
how about tabRegister?

2021-09-07 03:20 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
I have already run two test cases inside my registerTests class at the same without error.
![image](https://user-images.githubusercontent.com/68154870/132279137-7ec31c30-d402-414d-bd2c-3b39d9995781.png)

2021-09-07 03:21 UTC, tanmle commented on src/test/java/tests/RegisterTests.java
>      private String password = DataHelper.getRandomPassword(10);
I missed this but we don't need to random password

2021-09-07 03:21 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
So please let me know where I should check to find error, thank you so much

2021-09-07 03:23 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
>      private String password = DataHelper.getRandomPassword(10);
thank you so much, I'll change that

2021-09-07 03:28 UTC, anhlvt commented on src/test/java/tests/RegisterTests.java
> +
The TC02 is using data of TC01 to run. How we can create account for TC02 if we use the email same with TC01??

2021-09-07 03:37 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
thank you so much for you explanation. I think that I'm using precondition method to create data for two tc07 and tc09, so each Tc has own separated data which means tc07 has own account data and tc09 has own account data.

2021-09-07 03:41 UTC, anhlvt commented on src/test/java/tests/RegisterTests.java
> +
Did you debug at register account on TC02 and see what happen?

2021-09-07 03:41 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
I'm so sorry, I had a big mistake, I should put beforemethod instead of beforetest

2021-09-07 03:47 UTC, anhlvt commented on src/test/java/tests/RegisterTests.java
> +
I think @BeforeMethod is good but you need to put this `private String email = DataHelper.getRandomEmail();` on pre-condition

2021-09-07 03:47 UTC, HoanVanHuynh commented on src/main/java/page_objects/BasePage.java
> +    private final By tabChangePassword = By.cssSelector(" a[href*='ChangePassword']");
thank you so much, I'll change tabRegister a little bit.

2021-09-07 04:00 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
thank you so much, I'll put that into precondition method instead of outside the method

2021-09-07 04:11 UTC, anhlvt commented on src/test/java/tests/RegisterTests.java
> +
You can declare a  email var outside and use Random inside pre-condition:
`
private String email;
public void precondition() {
         email = DataHelper.getRandomEmail()
    }`

2021-09-07 04:32 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
thank you so much, I understood , oh I'm so stupid

2021-09-07 04:43 UTC, anhlvt approved these changes

2021-09-07 04:44 UTC, merged

2021-09-07 04:44 UTC, HoanVanHuynh commented on src/test/java/tests/RegisterTests.java
> +
Each Tc inside my registertests has own separated data such as email, pid. Thank you so much Mr. Anh