User can cancel a ticket
HoanVanHuynh/test-cases-selenium-framework-hoan pull request #9
Opened 2021-09-07 06:37 UTC by HoanVanHuynh

User can cancel a ticket

2021-09-07 06:52 UTC, tanmle requested changes

2021-09-07 06:52 UTC, tanmle commented on src/main/java/page_objects/BookTicketPage.java
> +        Wait.untilElementIsVisible(lblBookTicketFormTitle, 10);
why don't you have a var for `10`?

2021-09-07 06:52 UTC, tanmle commented on src/main/java/page_objects/BookTicketPage.java
> +    public String getInformationBeforeBooking(Ticket ticket) {
line 105 to line 134 are too complicated to solve simple math, try another way.

2021-09-07 06:52 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    public void clickOKButton() {
working with alert is not something like this. You should just have one method `acceptAlert` in DriverHelper

2021-09-07 06:52 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    public String getCancelTicketNoteWith0Or1Ticket(int ticketAmount, int maximumTicketAmount) {
getCancelTicketNoteWith0Or1Ticket
getCancelTicketNoteWithMoreThan1Ticket
try to use 1 method for 2 scenarios.

2021-09-07 07:11 UTC, HoanVanHuynh commented on src/main/java/page_objects/BookTicketPage.java
> +        Wait.untilElementIsVisible(lblBookTicketFormTitle, 10);
Thank you for the question. I'll fix that

2021-09-07 07:12 UTC, HoanVanHuynh commented on src/main/java/page_objects/BookTicketPage.java
> +    public String getInformationBeforeBooking(Ticket ticket) {
Thank you so much. I'll try another way for that problem

2021-09-07 07:13 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    public void clickOKButton() {
Thank you so much. I'll add another method for alert

2021-09-07 07:14 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    public String getCancelTicketNoteWith0Or1Ticket(int ticketAmount, int maximumTicketAmount) {
Thank you so much. I'll try to create 1 method

2021-09-07 08:51 UTC, tanmle requested changes

2021-09-07 08:51 UTC, tanmle commented on src/main/java/helpers/DriverHelper.java
> +    public static Alert getAlert() {
you don't need to get alert, call `getDriver()..switchTo().alert().accept();` inside `acceptAlert` is fine.

2021-09-07 08:51 UTC, tanmle commented on src/main/java/page_objects/BookTicketPage.java
> +    public boolean isTheSameTicketInformationDisplayed(Ticket ticket) {
this is not good either.

2021-09-07 08:51 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    public String getCancelTicketNote(int ticketAmount, int maximumTicketAmount) {
why don't you just capture the note element without the text, then in the test script you get the note's text then compare?

2021-09-07 08:54 UTC, HoanVanHuynh commented on src/main/java/helpers/DriverHelper.java
> +    public static Alert getAlert() {
thank you so much. I'll change that

2021-09-07 08:55 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    public String getCancelTicketNote(int ticketAmount, int maximumTicketAmount) {
Thank you so much. That's a great idea. I'll do it immediately

2021-09-07 08:56 UTC, HoanVanHuynh commented on src/main/java/page_objects/BookTicketPage.java
> +    public boolean isTheSameTicketInformationDisplayed(Ticket ticket) {
I'll try to define another one

2021-09-07 10:01 UTC, tanmle requested changes

2021-09-07 10:01 UTC, tanmle commented on src/main/java/page_objects/BookTicketPage.java
> +    public boolean isTheSameTicketInformationDisplayed(Ticket ticket) {
try another way, you can refer to the others in the same test case group with you.

2021-09-07 10:01 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    public WebElement getCancelTicketNote(int ticketAmount, int maximumTicketAmount) {
did you fix this?

2021-09-07 10:02 UTC, tanmle requested changes

2021-09-07 10:02 UTC, tanmle commented on src/test/java/tests/CancelTicketTests.java
> +        String actualBeforeCancellingResult = myTicketPage.getCancelTicketNote(2, 10).getText();
this is not correct. you already capture the element by text then you get its text to compare.

2021-09-07 10:09 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    public WebElement getCancelTicketNote(int ticketAmount, int maximumTicketAmount) {
Yes, I did. But I misunderstood what you want me to fix. I'll fix that again. Thank you so much

2021-09-07 10:10 UTC, HoanVanHuynh commented on src/test/java/tests/CancelTicketTests.java
> +        String actualBeforeCancellingResult = myTicketPage.getCancelTicketNote(2, 10).getText();
I'm sorry. I misunderstood what you want me to fix. I'll change that again. Thank you so much

2021-09-07 12:09 UTC, tanmle requested changes

2021-09-07 12:09 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    private final String dynamicNoteWith0Or1Ticket = "//div[@class='message']/li[text()='You currently book %d ticket, you can book %d more.']";
I'm still seeing this.

2021-09-07 14:17 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    private final String dynamicNoteWith0Or1Ticket = "//div[@class='message']/li[text()='You currently book %d ticket, you can book %d more.']";
I have to have two dynamic notes because two cases will happen when we book or cancel: first one is: you currently book...ticket,  second one is: you currently...tickets. The difference between them is s depending on number of tickets. So please let me know how to solve my problem. Thank you so much

2021-09-08 00:36 UTC, tanmle requested changes

2021-09-08 00:36 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    private final String dynamicNoteWith0Or1Ticket = "//div[@class='message']/li[text()='You currently book %d ticket, you can book %d more.']";
then you didn't understand my suggestion, why don't you capture that note without using the text, then get its text to compare in the test script.

2021-09-08 01:41 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    private final String dynamicNoteWith0Or1Ticket = "//div[@class='message']/li[text()='You currently book %d ticket, you can book %d more.']";
thank you so much, I've got it.

2021-09-09 01:34 UTC, anhlvt commented on src/main/java/page_objects/ChangePasswordPage.java
> +    public void changePassword(String ctp, String np, String cmp) {
the var should be more clear

2021-09-09 01:46 UTC, anhlvt commented on src/main/java/page_objects/BookTicketPage.java
> +        departDate.isVisible(Constants.TIME_WAIT);
This should be replaced by waitForVisibility(). 
Ex: ` Button xxx = new Button("");
        xxx.waitForVisibility();`

2021-09-09 01:46 UTC, HoanVanHuynh commented on src/main/java/page_objects/ChangePasswordPage.java
> +    public void changePassword(String ctp, String np, String cmp) {
Thank you so much. I'll change all my variable a little bit

2021-09-09 01:50 UTC, HoanVanHuynh commented on src/main/java/page_objects/BookTicketPage.java
> +        departDate.isVisible(Constants.TIME_WAIT);
Thank you so much. I'll fix that

2021-09-09 02:19 UTC, anhlvt commented on src/main/java/page_objects/RegisterPage.java
> +        registerSuccessMessage.isExist(Constants.TIME_WAIT);
you miss here

2021-09-09 02:21 UTC, HoanVanHuynh commented on src/main/java/page_objects/RegisterPage.java
> +        registerSuccessMessage.isExist(Constants.TIME_WAIT);
I'm so sorry

2021-09-09 02:58 UTC, tanmle commented on src/main/java/helpers/DriverHelper.java
> +    public static void acceptAlert() {
do you still need to accept alert here?

2021-09-09 02:58 UTC, tanmle commented on src/test/java/tests/CancelTicketTests.java
> +        String expectedBeforeCancellingResult = "You currently book 2 tickets, you can book 8 more.";
you should dynamic the number here, depends on your ticket amount.

2021-09-09 03:26 UTC, HoanVanHuynh commented on src/main/java/helpers/DriverHelper.java
> +    public static void acceptAlert() {
Thank you for the question. I'll delete the acceptAlert method.

2021-09-09 03:29 UTC, HoanVanHuynh commented on src/test/java/tests/CancelTicketTests.java
> +        String expectedBeforeCancellingResult = "You currently book 2 tickets, you can book 8 more.";
Thank you for your suggestion. I'll define a new method for that

2021-09-09 05:12 UTC, tanmle requested changes

2021-09-09 05:12 UTC, tanmle commented on src/main/java/page_objects/ChangePasswordPage.java
> +        currentPassword.setValue(old);
you should use set value in cases of no other choice, use enter instead.

2021-09-09 05:12 UTC, tanmle commented on src/main/java/page_objects/ChangePasswordPage.java
> +    public void changePassword(String old, String fresh, String confirm) {
why don't you just name them current password, new password, confirm password?

2021-09-09 05:12 UTC, tanmle commented on src/main/java/page_objects/MyTicketPage.java
> +    public String getCancellingTicketResult(String ticketAmount, String maximumAmount) {
misunderstanding again, you don't need to have a method to return a string.

2021-09-09 05:12 UTC, tanmle commented on src/main/java/page_objects/BookTicketPage.java
> +    public boolean isTheSameTicketInformationDisplayed(String option) {
this method is not correct again, use following-sibling for just one selector and pass all the ticket information.

2021-09-09 05:22 UTC, HoanVanHuynh commented on src/main/java/page_objects/ChangePasswordPage.java
> +        currentPassword.setValue(old);
thank you so much. I'll change that

2021-09-09 05:23 UTC, HoanVanHuynh commented on src/main/java/page_objects/ChangePasswordPage.java
> +    public void changePassword(String old, String fresh, String confirm) {
thank you so much. I'll change that

2021-09-09 05:24 UTC, HoanVanHuynh commented on src/main/java/page_objects/MyTicketPage.java
> +    public String getCancellingTicketResult(String ticketAmount, String maximumAmount) {
thank you so much. I'm so sorry,  I'll change that

2021-09-09 05:24 UTC, HoanVanHuynh commented on src/main/java/page_objects/BookTicketPage.java
> +    public boolean isTheSameTicketInformationDisplayed(String option) {
thank you so much. I'll rewrite the method

2021-09-09 10:21 UTC, tanmle requested changes

2021-09-09 10:21 UTC, tanmle commented on src/main/java/page_objects/BookTicketPage.java
> +        dynamicBookedTicketTable.setDynamicValue(ticket.getDepartDate());
not like this Hoan, try to debug, then you will see what happen with dynamicBookedTicketTable

2021-09-09 10:47 UTC, HoanVanHuynh commented on src/main/java/page_objects/BookTicketPage.java
> +        dynamicBookedTicketTable.setDynamicValue(ticket.getDepartDate());
thank you so much. I'll rewrite the method

2021-09-09 11:47 UTC, tanmle commented on src/main/java/page_objects/LoginPage.java
> +    private final TextBox usernameField = new TextBox("id=username");
why don't you keep the naming for the controls? like txt, btn...

2021-09-09 12:27 UTC, HoanVanHuynh commented on src/main/java/page_objects/LoginPage.java
> +    private final TextBox usernameField = new TextBox("id=username");
I'm so sorry. I follow the way you name the controls without txt,..yesterday. I'll rename them again. Thank you so much

2021-09-09 13:09 UTC, tanmle approved these changes

2021-09-09 14:35 UTC, MinhQuan119 commented on src/main/java/page_objects/HomePage.java
> +    private final Label lblWelcomeContentAtTop = new Label("css=div#content h1");
if you just have 1 Welcome header, then no need to add location for it, lblWelcomeContent is good enough

2021-09-09 14:38 UTC, MinhQuan119 commented on src/main/java/page_objects/HomePage.java
> +    private final Label lblWelcomeContentAtTop = new Label("css=div#content h1");
please check for other pages also

2021-09-09 15:15 UTC, HoanVanHuynh commented on src/main/java/page_objects/HomePage.java
> +    private final Label lblWelcomeContentAtTop = new Label("css=div#content h1");
thank you so much. I'll check for my pages

2021-09-10 07:48 UTC, MinhQuan119 approved these changes

2021-09-10 07:48 UTC, merged